volumes:
  redpanda_data:
  postgres_data:
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command: redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M --node-id 0 --check --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092 --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    ports:
      - 9092:9092
    env_file:
      - .env
  postgres:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
